---
  - name: Sleep for 300 seconds and continue with play
    wait_for:
      timeout: 300
    delegate_to: localhost

  - name: Gathering Local Server facts
    setup:
    register: setup_info
    delegate_to: localhost

  - name: Show Deployment Server IP Address Information
    debug:
      msg: "Local Ip Addres is: {{ setup_info.ansible_facts.ansible_default_ipv4.address }}"

  - name: Configure Apache sites-available 000-default.conf
    replace:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '(.*)DocumentRoot(.*)$'
      replace: 'DocumentRoot /home/hpe/ansible/ansible-sap-hana-deploy-sles/setup/html'
    become: yes
    run_once: true
    delegate_to: localhost

  - name: Configure Apache sites-available default-ssl.conf
    replace:
      path: /etc/apache2/sites-available/default-ssl.conf
      regexp: '(.*)DocumentRoot(.*)$'
      replace: 'DocumentRoot /home/hpe/ansible/ansible-sap-hana-deploy-sles/setup/html'
    become: yes
    run_once: true
    delegate_to: localhost

  - name: Starting Internal Web Site
    service:
      name: apache2
      state: restarted
    run_once: true
    become: yes
    delegate_to: localhost

  - name: Server Powered Off
    hpilo_boot:
      host: "{{ server_hardware_ilo_ip }}"
      login: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      state: poweroff
    delegate_to: localhost

  - name: Task to boot a system using an ISO from an HP iLO interface
    hpilo_boot:
      host: "{{ server_hardware_ilo_ip }}"
      login: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      media: cdrom
      image: http://{{ setup_info.ansible_facts.ansible_default_ipv4.address }}/media/{{ installation_media }}
      state: boot_always
    delegate_to: localhost
